### ISSUE TITLE
infinite recursion of picireny

### ISSUE THREAD

**Issue by zhangxiaosa** [renatahodovan/picireny#35]
Hi, I installed picireny 21.8 through `pip install .`, with picire 21.8 and antlerinator 1!3.0.0.
When parsing case clang-22382 https://github.com/uw-pluverse/perses/blob/master/benchmark/clang-22382/small.c, I got an infinite recursion.

> Traceback (most recent call last):
>   File "/home/coq/anaconda3/envs/new_environment/bin/picireny", line 8, in <module>
>     sys.exit(execute())
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/cli.py", line 342, in execute
>     skip_whitespace=args.skip_whitespace)
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/cli.py", line 222, in reduce
>     log_tree('Initial tree', hdd_tree)
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/cli.py", line 125, in log_tree
>     info.height(hdd_tree),
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/info.py", line 53, in height
>     if isinstance(node, HDDRule) and node.state == node.KEEP else 0)
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/info.py", line 52, in <genexpr>
>     return 1 + (max((height(child) for child in node.children), default=0)
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/info.py", line 53, in height
>     if isinstance(node, HDDRule) and node.state == node.KEEP else 0)
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/info.py", line 52, in <genexpr>
>     return 1 + (max((height(child) for child in node.children), default=0)
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/info.py", line 53, in height
>     if isinstance(node, HDDRule) and node.state == node.KEEP else 0)
>   ......
>   ......
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/info.py", line 53, in height
>     if isinstance(node, HDDRule) and node.state == node.KEEP else 0)
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/info.py", line 52, in <genexpr>
>     return 1 + (max((height(child) for child in node.children), default=0)
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/info.py", line 53, in height
>     if isinstance(node, HDDRule) and node.state == node.KEEP else 0)
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/info.py", line 52, in <genexpr>
>     return 1 + (max((height(child) for child in node.children), default=0)
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/info.py", line 53, in height
>     if isinstance(node, HDDRule) and node.state == node.KEEP else 0)
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/info.py", line 52, in <genexpr>
>     return 1 + (max((height(child) for child in node.children), default=0)
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/info.py", line 53, in height
>     if isinstance(node, HDDRule) and node.state == node.KEEP else 0)
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/info.py", line 52, in <genexpr>
>     return 1 + (max((height(child) for child in node.children), default=0)
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/info.py", line 53, in height
>     if isinstance(node, HDDRule) and node.state == node.KEEP else 0)
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/info.py", line 52, in <genexpr>
>     return 1 + (max((height(child) for child in node.children), default=0)
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/info.py", line 53, in height
>     if isinstance(node, HDDRule) and node.state == node.KEEP else 0)
>   File "/home/coq/anaconda3/envs/new_environment/lib/python3.7/site-packages/picireny/info.py", line 52, in <genexpr>
>     return 1 + (max((height(child) for child in node.children), default=0)
> RecursionError: maximum recursion depth exceeded

Here is my command: 

> picireny -i small.c --test r.sh --srcml:language C --grammar C.g4 --start compilationUnit --cache none

I also tried other versions such as 19.3 and got the same error.

Is it a bug? Could you tell me how to bypass it? Thank you!

**Comment by renatahodovan** [comment]
@zhangxiaosa Thanks for the report! It seems that the parse tree, created by the C grammar, is too deep for the current recursion limit of your Python interpreter. Increasing this limit to a large value, e.g., with `--sys-recursion-limit=100000` should make the issue go away.

Please tell me if it solved your issue.

**Comment by zhangxiaosa** [comment]
Thank you, this flag prevents the infinite recursion.

**Comment by akosthekiss** [comment]
@zhangxiaosa An extra note: I have spotted `--srcml:language C --grammar C.g4` on your command line. These should be either/or. Although the tool does not complain if both are specified, only one of them is taken into account (`--grammar C.g4` will be used, `--srcml:language C` will be skipped).

The background: Picireny uses a tree representation of the input internally to perform the reduction. Currently, two ways are supported to build this internal tree representation: one of the methods uses srcML to process the input, the other uses ANTLR v4. There is a command line option `--builder ...` that can be used to specify the method to be used. If it is not specified, `--builder antlr4` is the default. Your command line options `--grammar C.g4 --start compilationUnit` are specific to the ANTLR v4 builder (actually, they are a shorthand for `--antlr4:grammar C.g4 --antlr4:start compilationUnit`, while (as its prefix suggests) the `--srcml:language C` option is specific to the srcML builder. (BTW, if you want to use the srcML builder, you have to have the `srcml` tool on your path.)

One more thing, more of a question than a note: I see you have disabled caching (`--cache none`). Is there any specific reason for that?

**Comment by zhangxiaosa** [comment]
Thank you for pointing this out. The reason why I disabled caching is to test the performance of ddmin of some of its variants, such as --subset-iterator skip.
